export const dataTestID = {
  appLogin: 'app-login',
  appHome: 'app-home',
  appHomeHeader: 'app-home-header',
  appHomeBody: 'app-home-body',
  appHomeFooter: 'app-home-footer',
  appOrderViewer: 'app-order-viewer',
  appOrderSubmitter: 'app-order-submitter',
  // login page
  loginUserName: 'login-username',
  loginPassword: 'login-password',
  loginShowPassword: 'login-show-password',
  loginButton: 'login-button',
  // home page
  logoutButton: 'logout-button',
  mobileHamburger: 'mobile-hamburger',
  mobileLogoutButton: 'mobile-logout-button',
  searchOrder: 'search-order',
  clearSearchOrder: 'clear-search-order',
  orderCard: 'order-card',
  deleteOrder: 'delete-order',
  newTableNoInput: 'new-table-no-input',
  newSizeInput: 'new-size-input',
  newCrustInput: 'new-crust-input',
  newFlavorInput: 'new-flavor-input',
  submitOrder: 'submit-order',
};
